apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    app: mynginx
  namespace: trabkubernetes
spec:
  containers:
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
          name: mynginx